[package]
name = "happy_chart_rs"
version = "1.10.3"
edition = "2021"
license = "GPL-3.0-only"
description = "A subjective day quality charting program"
keywords = ["happy","chart","mental-health","binary","executable"]
readme = "README.MD"
repository = "https://github.com/CoryRobertson/happy_chart_rs"
homepage = "https://github.com/CoryRobertson/happy_chart_rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
lto = true

[dependencies]
eframe = { version = "0.23.0", features = ["serde"]}
egui = { version = "0.23.0", features = ["serde"]}
serde = { version = "1.0.183", features = ["derive"] }
chrono = { version = "0.4.26", features = ["serde"] }
chrono-tz = { version = "0.8.3", features = ["serde"] }
serde_json = "1.0.104"
rfd = "0.12.1"
image = "0.24.7"
# deflate should be used for release packages
# example file name:
# happy_chart_rs-v1.10.2-x86_64-pc-windows-msvc.zip
self_update = { version = "0.39.0", features = ["archive-zip","compression-flate2","compression-zip-bzip2","compression-zip-deflate"]}

[build-dependencies]
vergen = { version = "8.2.4", features = ["build","git","gitcl"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
