[package]
name = "happy_chart_rs"
version = "1.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0
lto = false

[profile.release]
overflow-checks = true
opt-level = 3
strip = true
debug-assertions = false
lto = true

[dependencies]
eframe = "0.19.0"
egui = "0.19.0"
serde = { version = "1.0.146", features = ["derive"] }
chrono = "0.4.23"
chrono-tz = { version = "0.8.1", features = ["serde"] }
serde_json = "1.0.85"