[package]
name = "happy_chart_rs"
version = "1.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0
lto = false

[profile.release]
overflow-checks = true
opt-level = 3
strip = true
debug-assertions = false
lto = true

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
serde = { version = "1.0.183", features = ["derive"] }
chrono = { version = "0.4.26", features = ["serde"] }
chrono-tz = { version = "0.8.3", features = ["serde"] }
serde_json = "1.0.104"

[build-dependencies]
vergen = { version = "8.2.4", features = ["build","git","gitcl"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
