[package]
name = "happy_chart_rs"
version = "1.8.0"
edition = "2021"
license = "GPL-3.0-only"
description = "A subjective day quality charting program"
keywords = ["happy","chart","mental-health","binary","executable"]
readme = "README.MD"
repository = "https://github.com/CoryRobertson/happy_chart_rs"
homepage = "https://github.com/CoryRobertson/happy_chart_rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
lto = true

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
serde = { version = "1.0.183", features = ["derive"] }
chrono = { version = "0.4.26", features = ["serde"] }
chrono-tz = { version = "0.8.3", features = ["serde"] }
serde_json = "1.0.104"
rfd = "0.11.4"
image = "0.24.7"

[build-dependencies]
vergen = { version = "8.2.4", features = ["build","git","gitcl"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
